import React from "react";
import { FaSmile, FaLaugh, FaSadTear, FaAngry, FaSurprise } from "react-icons/fa";

export const EmojiPicker = ({ onSelect }) => {
  const emojis = [
    { icon: "😀", label: "Grinning" },
    { icon: "😃", label: "Smiling" },
    { icon: "😄", label: "Happy" },
    { icon: "😁", label: "Beaming" },
    { icon: "😆", label: "Laughing" },
    { icon: "😅", label: "Sweat smile" },
    { icon: "🤣", label: "Rolling laugh" },
    { icon: "😂", label: "Tears of joy" },
    { icon: "🙂", label: "Slight smile" },
    { icon: "🙃", label: "Upside down" },
    { icon: "😉", label: "Wink" },
    { icon: "😊", label: "Smiling eyes" },
    { icon: "😇", label: "Halo" },
    { icon: "🥰", label: "Hearts" },
    { icon: "😍", label: "Heart eyes" },
    { icon: "🤩", label: "Star eyes" },
    { icon: "😘", label: "Kiss" },
    { icon: "😗", label: "Kissing" },
    { icon: "☺️", label: "Smiling" },
    { icon: "😚", label: "Kissing closed" },
    { icon: "😙", label: "Kissing smiling" },
    { icon: "🥲", label: "Tear smile" },
    { icon: "😋", label: "Yum" },
    { icon: "😛", label: "Tongue" },
    { icon: "😜", label: "Wink tongue" },
    { icon: "😝", label: "Squint tongue" },
    { icon: "🤑", label: "Money" },
    { icon: "🤗", label: "Hugging" },
    { icon: "🤭", label: "Hand mouth" },
    { icon: "🤫", label: "Shushing" },
    { icon: "🤔", label: "Thinking" },
    { icon: "🤐", label: "Zipper mouth" },
    { icon: "🤨", label: "Raised eyebrow" },
    { icon: "😐", label: "Neutral" },
    { icon: "😑", label: "Expressionless" },
    { icon: "😶", label: "No mouth" },
    { icon: "😏", label: "Smirk" },
    { icon: "😒", label: "Unamused" },
    { icon: "🙄", label: "Rolling eyes" },
    { icon: "😬", label: "Grimace" },
    { icon: "🤥", label: "Lying" },
    { icon: "😌", label: "Relieved" },
    { icon: "😔", label: "Pensive" },
    { icon: "😪", label: "Sleepy" },
    { icon: "🤤", label: "Drooling" },
    { icon: "😴", label: "Sleeping" },
    { icon: "😷", label: "Medical mask" },
    { icon: "🤒", label: "Thermometer" },
    { icon: "🤕", label: "Head bandage" },
    { icon: "🤢", label: "Nauseated" },
    { icon: "🤮", label: "Vomiting" },
    { icon: "🤧", label: "Sneezing" },
    { icon: "🥵", label: "Hot" },
    { icon: "🥶", label: "Cold" },
    { icon: "🥴", label: "Woozy" },
    { icon: "😵", label: "Dizzy" },
    { icon: "🤯", label: "Exploding head" },
    { icon: "🤠", label: "Cowboy" },
    { icon: "🥳", label: "Partying" },
    { icon: "🥸", label: "Disguised" },
    { icon: "😎", label: "Sunglasses" },
    { icon: "🤓", label: "Nerd" },
    { icon: "🧐", label: "Monocle" },
    { icon: "😕", label: "Confused" },
    { icon: "😟", label: "Worried" },
    { icon: "🙁", label: "Slight frown" },
    { icon: "☹️", label: "Frowning" },
    { icon: "😮", label: "Surprised" },
    { icon: "😯", label: "Hushed" },
    { icon: "😲", label: "Astonished" },
    { icon: "😳", label: "Flushed" },
    { icon: "🥺", label: "Pleading" },
    { icon: "😦", label: "Frowning open" },
    { icon: "😧", label: "Anguished" },
    { icon: "😨", label: "Fearful" },
    { icon: "😰", label: "Anxious sweat" },
    { icon: "😥", label: "Sad relieved" },
    { icon: "😢", label: "Crying" },
    { icon: "😭", label: "Loudly crying" },
    { icon: "😱", label: "Screaming" },
    { icon: "😖", label: "Confounded" },
    { icon: "😣", label: "Persevering" },
    { icon: "😞", label: "Disappointed" },
    { icon: "😓", label: "Downcast sweat" },
    { icon: "😩", label: "Weary" },
    { icon: "😫", label: "Tired" },
    { icon: "🥱", label: "Yawning" },
    { icon: "😤", label: "Triumph" },
    { icon: "😡", label: "Pouting" },
    { icon: "😠", label: "Angry" },
    { icon: "🤬", label: "Swearing" },
    { icon: "😈", label: "Smiling horns" },
    { icon: "👿", label: "Angry horns" },
    { icon: "💀", label: "Skull" },
    { icon: "☠️", label: "Skull crossbones" },
    { icon: "💩", label: "Pile of poo" },
    { icon: "🤡", label: "Clown" },
    { icon: "👹", label: "Ogre" },
    { icon: "👺", label: "Goblin" },
    { icon: "👻", label: "Ghost" },
    { icon: "👽", label: "Alien" },
    { icon: "👾", label: "Alien monster" },
    { icon: "🤖", label: "Robot" },
    { icon: "😺", label: "Grinning cat" },
    { icon: "😸", label: "Smiling cat eyes" },
    { icon: "😹", label: "Tears of joy cat" },
    { icon: "😻", label: "Heart eyes cat" },
    { icon: "😼", label: "Smirk cat" },
    { icon: "😽", label: "Kissing cat" },
    { icon: "🙀", label: "Weary cat" },
    { icon: "😿", label: "Crying cat" },
    { icon: "😾", label: "Pouting cat" },
  ];

  return (
    <div className="bg-white rounded-xl shadow-lg p-3 w-64 h-64 overflow-y-auto custom-scrollbar border border-gray-200">
      <div className="grid grid-cols-8 gap-1">
        {emojis.map((emoji, index) => (
          <button
            key={index}
            className="text-xl p-1 hover:bg-purple-100 rounded-md transition-colors"
            onClick={() => onSelect(emoji.icon)}
            aria-label={emoji.label}
          >
            {emoji.icon}
          </button>
        ))}
      </div>
    </div>
  );
};